/// Flutter icons VideoIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VideoIcons
///      fonts:
///       - asset: fonts/VideoIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlickVideoIcons {
  FlickVideoIcons._();

  static const _kFontFam = 'VideoIcons';
  static const String? _kFontPkg = null;

  static const IconData cog =
      IconData(0xf013, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xf078, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
